apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: mynamespace
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: mynamespace
  labels: 
    app: cart
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: cart
      project: roboshop
      tier: app
  template:
    metadata:
      labels: 
        app: cart
        project: roboshop
        tier: app
    spec:
      containers:
      - name: cart
        image: sreenathsri/cart:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: mynamespace
spec:
  selector:
    app: cart
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 
    targetPort: 8080 