apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mynamespace
  labels:
    app: mongodb
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      project: roboshop
      tier: db
  template:
    metadata:
      labels:
        app: mongodb
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mongodb
        image: sreenathsri/mongodb:v1
        imagePullPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mynamespace
spec:
  selector:
    app: mongodb
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017